id: I3B2AAC2E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:28:23+00:00'
last_modified: '2022-06-15T18:42:44.965681+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN641
  title: དཔལ་སྤུངས་ཆོས་སྤྱོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8986':
      image_group_id: I3CN643
      title: Volume 1 of dpal spungs chos spyod/
      total_pages: 588
      order: 1
      base_file: 8986.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
