id: I3B2AAC2E
legacy_id: P000460
ocr_import_info:
  bdrc_scan_id: W3CN641
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T21:25:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T15:16:55.525970+00:00'
last_modified: 2022-09-03 23:17:08.539996
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN641
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN641
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་སྤུངས་ཆོས་སྤྱོད།
statistics:
  ocr_word_mean_confidence_index: 0.5784120834472865
  ocr_word_median_confidence_index: 0.5799999833106995
quality: null
bases:
  I3CN643:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN643
      total_pages: 588
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN643.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5784120834472865
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
